### 1. การตั้งค่าสภาพแวดล้อม (Environment Setup)
ขั้นตอนเริ่มต้นด้วยการเชื่อมต่อ Google Drive เพื่อเข้าถึงไฟล์ข้อมูล และย้าย Directory ไปยังโฟลเดอร์ของโปรเจกต์

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/SED6XX_NLP_project

/content/drive/MyDrive/Colab Notebooks/SED6XX_NLP_project

### 2. การเตรียมข้อมูล (Data Preparation)
โหลดข้อมูลข่าวจาก Prachatai ซึ่งแบ่งเป็นชุด Train, Test และ Validation โดยใช้ Pandas และตรวจสอบการกระจายตัวของ Tag (Multi-label) ต่างๆ

In [ ]:
from transformers import AutoModel, AutoTokenizer ,AutoModelForCausalLM
model_TH = "airesearch/wangchanberta-base-att-spm-uncased"

In [ ]:
import pandas as pd
data_train = pd.read_csv('prachatai_train.csv')
data_test = pd.read_csv('prachatai_test.csv')
data_val = pd.read_csv('prachatai_validation.csv')

In [ ]:
data_test

,Unnamed: 0,url,date,title,body_text,politics,human_rights,quality_of_life,international,social,environment,economics,culture,labor,national_security,ict,education
0,0,https://prachatai.com/print/62490,2015-11-17 18:14,แฮคเกอร์ Anonymous ลั่นทำสงครามไซเบอร์ครั้งใหญ...,17 พ.ย. 2558 Blognone [1] รายงานว่า กลุ่มแฮคเก...,0,0,0,1,0,0,0,0,0,0,1,0
1,1,https://prachatai.com/print/48181,2013-08-14 20:08,สตูดิโอจิบลิต้านสงคราม วิจารณ์การแก้รัฐธรรมนูญ...,ขณะที่ ส.ส. ญี่ปุ่นต้องการแก้รัฐธรรมนูญเพื่อเป...,0,0,0,1,0,0,0,0,0,0,0,0
2,2,https://prachatai.com/print/63379,2016-01-09 13:43,We need Safety Zone สมาคมเพื่อสันติภาพนำเดินรณ...,สมาคมเพื่อสันติภาพ นำเครือข่ายเด็กและเยาวชน ภา...,1,0,0,0,1,0,0,0,0,1,0,0
3,3,https://prachatai.com/print/74297,2017-11-26 09:17,รัตโก มลาดิช ทหารใหญ่กองกำลังชาวเซิร์บถูกตัดสิ...,อดีตเสนาธิการกองทัพเซิร์บบอสเนีย รัตโก มลาดิช ...,0,1,0,1,0,0,0,0,0,0,0,0
4,4,https://prachatai.com/print/8103,2006-04-10 18:55,พันธมิตรฯใต้เตรียมฟ้อง กกต.เอื้อประโยชน์ให้ไทย...,ประชาไท - มติพันธมิตรฯ ภาคใต้เดินหน้าจัดเวทีปฏ...,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6784,6784,https://prachatai.com/print/37101,2011-09-27 21:43,คุยกับผู้ประสานงานเครือข่ายพลเมืองเน็ต: รัฐประ...,คุยกับอาทิตย์ สุริยะวงศ์กุล ผู้ประสานงานเครือข...,1,1,0,0,0,0,0,0,0,0,1,0
6785,6785,https://prachatai.com/print/7027,2006-01-18 04:55,ส.ว.แจ้งความดำเนินคดี คตง.ไม่คืนตำแหน่งจารุวรรณ,ประชาไท - 18 ต.ค.48 พล.ต.อินทรัตน์ ยอดบาง...,1,0,0,0,0,0,0,0,0,0,0,0
6786,6786,https://prachatai.com/print/68204,2016-10-05 13:29,ประยุทธ์ปัดตอบปมกักตัว 'โจชัว หว่อง' นักเคลื่อ...,5 ต.ค. 2559 จากกรณี โจชัว หว่อง แกนนำนักเรียนน...,1,1,0,1,0,0,0,0,0,0,0,0
6787,6787,https://prachatai.com/print/50808,2013-12-30 05:10,สมัครเลือกตั้ง ปัตตานี-ยะลา-นราธิวาส วันที่สอง...,'ซูการ์โน มะทา' นำผู้สมัคร ส.ส.เพื่อไทยลงครบ 3...,1,0,0,0,0,0,0,0,0,0,0,0
6788,6788,https://prachatai.com/print/16119,2008-03-20 15:29,ปักกิ่งเมินนองเลือด ประกาศไม่เปลี่ยนแปลงเส้นทา...,นักท่องเที่ยวถ่ายรูปคู่กับสระว่ายน้ำยิงตง (Yin...,1,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
tags = [
    'politics',
    'human_rights',
    'quality_of_life',
    'international',
    'social',
    'environment',
    'economics',
    'culture',
    'labor',
    'national_security',
    'ict',
    'education',
]

dict_tag_train = {tag:int(data_train[tag].value_counts()[1]) for tag in tags}
dict_tag_test = {tag:int(data_test[tag].value_counts()[1]) for tag in tags}
dict_tag_val = {tag:int(data_val[tag].value_counts()[1]) for tag in tags}

df_count_train = pd.DataFrame(list(dict_tag_train.items()), columns=['tag', 'count'])
df_count_test = pd.DataFrame(list(dict_tag_test.items()), columns=['tag', 'count'])
df_count_val = pd.DataFrame(list(dict_tag_val.items()), columns=['tag', 'count'])

In [ ]:
df_count_val

                  tag  count
0            politics   3852
1        human_rights   1458
2     quality_of_life   1144
3       international    828
4              social    782
5         environment    764
6           economics    487
7             culture    388
8               labor    375
9   national_security    339
10                ict    285
11          education    248

### 3. การทำ Tokenization และเตรียม Dataset
ใช้ `WangchanBERTa` เป็นโมเดลหลัก โดยทำการ Tokenize ข้อความและแปลง Pandas DataFrame ให้เป็น Hugging Face Dataset พร้อมทั้งกำหนด Labels สำหรับการทำ Multi-label Classification

In [ ]:
from transformers import AutoModelForSequenceClassification , TrainingArguments, Trainer, DataCollatorWithPadding
import torch

model = AutoModelForSequenceClassification.from_pretrained(
    model_TH,
    num_labels=len(tags),
    problem_type="multi_label_classification"
)
tokenizer = AutoTokenizer.from_pretrained(model_TH, use_fast=False)

MAX_LEN = 128

from datasets import Dataset

def tokenize_fn(example):
    tokens = tokenizer(example['body_text'],
                      truncation=True,
                      max_length=MAX_LEN,
                      padding=False)  # Don't pad here, let DataCollator handle it
    # Add labels for multi-label classification
    labels = [float(example[tag]) for tag in tags]
    tokens['labels'] = labels
    return tokens

# Convert pandas DataFrames to Hugging Face datasets
train_dataset = Dataset.from_pandas(data_train)
val_dataset = Dataset.from_pandas(data_val)

# Apply tokenization
tokenized = {
    "train": train_dataset.map(tokenize_fn, remove_columns=train_dataset.column_names),
    "validation": val_dataset.map(tokenize_fn, remove_columns=val_dataset.column_names)
}

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at airesearch/wangchanberta-base-att-spm-uncased and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/54379 [00:00<?, ? examples/s]

Map:   0%|          | 0/6721 [00:00<?, ? examples/s]

### 4. การกำหนด Metric และการฝึกฝนโมเดル (Model Training)
กำหนดฟังก์ชัน `compute_metrics` เพื่อวัดผลด้วย F1-Score (Micro/Macro) และเริ่มการ Train ด้วย `Trainer` API ของ Hugging Face

In [ ]:
tokenized["train"].take(2)[1]

{'input_ids': [5,
  10,
  601,
  1003,
  425,
  11236,
  6840,
  641,
  9550,
  2173,
  7130,
  8565,
  10,
  1388,
  14155,
  166,
  26,
  10575,
  336,
  5129,
  7642,
  7801,
  83,
  1370,
  947,
  32,
  605,
  480,
  357,
  10,
  76,
  162,
  11,
  10,
  2425,
  5210,
  3272,
  10496,
  275,
  2982,
  425,
  5221,
  734,
  472,
  947,
  636,
  1984,
  641,
  985,
  497,
  3548,
  2633,
  17663,
  16,
  21727,
  10,
  12,
  622,
  1304,
  12430,
  35,
  600,
  501,
  112,
  513,
  8565,
  952,
  2643,
  746,
  10,
  8519,
  7515,
  2190,
  10,
  579,
  9130,
  2124,
  4526,
  7182,
  351,
  8565,
  3925,
  22,
  10,
  409,
  10,
  1123,
  10,
  3478,
  97,
  668,
  2246,
  10,
  460,
  377,
  10,
  65,
  10,
  168,
  222,
  622,
  702,
  980,
  567,
  968,
  760,
  8565,
  308,
  45,
  10,
  4435,
  8953,
  8565,
  2499,
  1898,
  4096,
  10,
  5098,
  7443,
  2212,
  46,
  289,
  10,
  22560,
  32,
  760,
  640,
  6],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'labels': [0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

In [ ]:
from sklearn.metrics import f1_score, precision_score, recall_score
import numpy as np

sigmoid = torch.nn.Sigmoid()

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    # Convert to numpy arrays if they aren't already
    if isinstance(logits, torch.Tensor):
        logits = logits.detach().cpu().numpy()
    if isinstance(labels, torch.Tensor):
        labels = labels.detach().cpu().numpy()

    # Apply sigmoid to get probabilities
    probs = 1 / (1 + np.exp(-logits))  # sigmoid function
    # Convert to binary predictions
    preds = (probs >= 0.5).astype(int)
    y_true = labels.astype(int)

    return {
        "f1_micro": f1_score(y_true, preds, average="micro", zero_division=0),
        "f1_macro": f1_score(y_true, preds, average="macro", zero_division=0),
        "precision_micro": precision_score(y_true, preds, average="micro", zero_division=0),
        "recall_micro": recall_score(y_true, preds, average="micro", zero_division=0)
    }

In [ ]:

OUTPUT_DIR = "wcberta-prachathai67k"
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    learning_rate=1e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    save_strategy="epoch",
    eval_strategy ="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_micro",
    greater_is_better=True,
    logging_steps=100,
    fp16=torch.cuda.is_available(),
    report_to="none",
    save_total_limit=2,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir=f"{OUTPUT_DIR}/logs",
    remove_unused_columns=True
   )


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

/tmp/ipython-input-2532528527.py:24: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 6, 'bos_token_id': 5}.

TrainOutput(global_step=67975, training_loss=0.1495006961689227, metrics={'train_runtime': 4787.8862, 'train_samples_per_second': 56.788, 'train_steps_per_second': 14.197, 'total_flos': 1.78862508893952e+16, 'train_loss': 0.1495006961689227, 'epoch': 5.0})

### 5. การเลือกโมเดลที่ดีที่สุดและส่งออก (Best Model Export)
ตรวจสอบ `trainer_state.json` เพื่อหา Checkpoint ที่ให้ผลลัพธ์ดีที่สุด จากนั้นโหลดโมเดลนั้นมาบันทึกแยกไว้ในโฟลเดอร์ `best` พร้อมกับไฟล์ชื่อ Class (label_names.json)

In [ ]:
test = Dataset.from_pandas(data_test)
tokenized_test = test.map(tokenize_fn, remove_columns=test.column_names)

Map:   0%|          | 0/6789 [00:00<?, ? examples/s]

In [ ]:
tokenized_test.take(2)[1]

{'input_ids': [5,
  2117,
  10,
  40,
  11,
  40,
  11,
  10,
  569,
  312,
  972,
  271,
  54,
  231,
  2763,
  792,
  1171,
  21,
  20573,
  24,
  12784,
  10,
  676,
  16,
  9739,
  10934,
  1332,
  554,
  1242,
  19,
  20549,
  1357,
  1579,
  10,
  3,
  6974,
  18,
  222,
  19,
  10622,
  327,
  17624,
  8159,
  18,
  10,
  6762,
  1802,
  7862,
  2328,
  14137,
  14262,
  108,
  1065,
  622,
  10,
  17318,
  9,
  9563,
  10,
  396,
  56,
  9,
  10300,
  10,
  3835,
  979,
  50,
  755,
  350,
  2970,
  13,
  676,
  4033,
  10,
  16,
  9739,
  10934,
  1332,
  599,
  273,
  2216,
  32,
  2843,
  79,
  19,
  3,
  3234,
  21433,
  1579,
  10,
  3,
  6974,
  18,
  10,
  9388,
  1351,
  9401,
  12,
  215,
  144,
  569,
  584,
  713,
  231,
  271,
  2407,
  379,
  1071,
  10,
  3748,
  14137,
  14262,
  108,
  31,
  287,
  1522,
  673,
  2117,
  10,
  40,
  11,
  40,
  11,
  10,
  559,
  10,
  3082,
  6],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'labels': [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

In [ ]:
from datasets import Dataset
test_data = data_test.loc[1:2,['body_text']+tags]
test_data = Dataset.from_pandas(test_data)
test_data_tok = test_data.map(tokenize_fn, remove_columns=test_data.column_names)

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

In [ ]:
test_data.take(2)[1]

{'body_text': 'สมาคมเพื่อสันติภาพ นำเครือข่ายเด็กและเยาวชน ภาคประชาสังคม 15 องค์กรร่วมเดินรณรงค์ยุติความรุนแรง สร้างพื้นที่ปลอดภัยเนื่องในเด็กแห่งชาติที่ปัตตานี\n\n\n\nเมื่อวันที่ 8 มกราคม 2559 สมาคมเพื่อสันติภาพชายแดนใต้และองค์กรภาคีเครือข่ายจัดกิจกรรม “พื้นที่ปลอดภัย หยุดความรุนแรงต่อเด็ก” เนื่องในงานวันเด็กแห่งชาติปี 2559 โดยการเดินรณรงค์ยุติความรุนแรงต่อเด็กและเยาวชนจากวิทยาลัยเทคนิคปัตตานี ผ่านถนนเจริญประดิษฐ์ เข้าสู่หอประชุมสำนักงานอธิการบดี มหาวิทยาลัยสงขลานครินทร์ (ม.อ.) วิทยาเขตปัตตานีเพื่ออ่านแถลงการณ์ของแต่ละองค์กร มีผู้เข้าร่วมประมาณ 500 คน\nโดยเครือข่ายเด็กและเยาวชนในเขตพื้นที่เทศบาลเมืองปัตตานี รวมถึงองค์กรภาคประชาสังคมที่เข้าร่วม15 องค์กร ประกอบด้วย1.สมาคมเพื่อสันติภาพชายแดนใต้2.ศูนย์เฝ้าระวังสถานการณ์ภาคใต้3.สถาบันสมุทรรัฐเอเชียตะวันออกเฉียงใต้ศึกษา ม.อ.ปัตตานี4.ชมรมนักศึกษารักสันติ5.ชมรม ม.อ.ทำดีเพื่อสังคม6.ชุมนุมสิงห์สันติภาพ 7.โรงเรียนเบญจมราชูทิศปัตตานี\n8.โรงเรียนเดชะปัตตนยานุกูล9.วิทยาลัยเทคนิคปัตตานี10.วิทยาลัยอาชีวศึกษาปัตตานี11.วิทยาลัยการอาชีพปัตตานี12.วิทยาลัยชุมชนปัตตานี13.สหพันธ์นักเรียน นักศึกษาเพื่อสันติภาพชายแดนใต้14.สโมสรนักศึกษาคณะรัฐศาสตร์ ม.อ.ปัตตานี15.ภาควิชาสังคม คณะมนุษยศาสตร์และสังคมศาสตร์ ม.อ.ปัตตานี\nวัตถุประสงค์ของกิจกรรมนี้เพื่อเรียกร้องให้ยุติการกระทำความรุนแรงต่อเด็กและเยาวชน และเพื่อสร้างพื้นที่ปลอดภัยแก่เด็กและเยาวชน ตลอดจนประชาชนผู้บริสุทธิ์ในพื้นที่จังหวัดชายแดนภาคใต้ เพื่อส่งเสริมและสนับสนุนการปฏิเสธความรุนแรงทุกรูปแบบในเขตพื้นที่จังหวัดชายแดนภาคใต้ และเพื่อต้องการให้ประชาชนมีบทบาทและเล็งเห็นความสำคัญของกระบวนการพูดคุยเพื่อสันติสุข',
 'politics': 1,
 'human_rights': 0,
 'quality_of_life': 0,
 'international': 0,
 'social': 1,
 'environment': 0,
 'economics': 0,
 'culture': 0,
 'labor': 0,
 'national_security': 1,
 'ict': 0,
 'education': 0}

In [ ]:
test_data.take(2)[1]

{'body_text': 'สมาคมเพื่อสันติภาพ นำเครือข่ายเด็กและเยาวชน ภาคประชาสังคม 15 องค์กรร่วมเดินรณรงค์ยุติความรุนแรง สร้างพื้นที่ปลอดภัยเนื่องในเด็กแห่งชาติที่ปัตตานี\n\n\n\nเมื่อวันที่ 8 มกราคม 2559 สมาคมเพื่อสันติภาพชายแดนใต้และองค์กรภาคีเครือข่ายจัดกิจกรรม “พื้นที่ปลอดภัย หยุดความรุนแรงต่อเด็ก” เนื่องในงานวันเด็กแห่งชาติปี 2559 โดยการเดินรณรงค์ยุติความรุนแรงต่อเด็กและเยาวชนจากวิทยาลัยเทคนิคปัตตานี ผ่านถนนเจริญประดิษฐ์ เข้าสู่หอประชุมสำนักงานอธิการบดี มหาวิทยาลัยสงขลานครินทร์ (ม.อ.) วิทยาเขตปัตตานีเพื่ออ่านแถลงการณ์ของแต่ละองค์กร มีผู้เข้าร่วมประมาณ 500 คน\nโดยเครือข่ายเด็กและเยาวชนในเขตพื้นที่เทศบาลเมืองปัตตานี รวมถึงองค์กรภาคประชาสังคมที่เข้าร่วม15 องค์กร ประกอบด้วย1.สมาคมเพื่อสันติภาพชายแดนใต้2.ศูนย์เฝ้าระวังสถานการณ์ภาคใต้3.สถาบันสมุทรรัฐเอเชียตะวันออกเฉียงใต้ศึกษา ม.อ.ปัตตานี4.ชมรมนักศึกษารักสันติ5.ชมรม ม.อ.ทำดีเพื่อสังคม6.ชุมนุมสิงห์สันติภาพ 7.โรงเรียนเบญจมราชูทิศปัตตานี\n8.โรงเรียนเดชะปัตตนยานุกูล9.วิทยาลัยเทคนิคปัตตานี10.วิทยาลัยอาชีวศึกษาปัตตานี11.วิทยาลัยการอาชีพปัตตานี12.วิทยาลัยชุมชนปัตตานี13.สหพันธ์นักเรียน นักศึกษาเพื่อสันติภาพชายแดนใต้14.สโมสรนักศึกษาคณะรัฐศาสตร์ ม.อ.ปัตตานี15.ภาควิชาสังคม คณะมนุษยศาสตร์และสังคมศาสตร์ ม.อ.ปัตตานี\nวัตถุประสงค์ของกิจกรรมนี้เพื่อเรียกร้องให้ยุติการกระทำความรุนแรงต่อเด็กและเยาวชน และเพื่อสร้างพื้นที่ปลอดภัยแก่เด็กและเยาวชน ตลอดจนประชาชนผู้บริสุทธิ์ในพื้นที่จังหวัดชายแดนภาคใต้ เพื่อส่งเสริมและสนับสนุนการปฏิเสธความรุนแรงทุกรูปแบบในเขตพื้นที่จังหวัดชายแดนภาคใต้ และเพื่อต้องการให้ประชาชนมีบทบาทและเล็งเห็นความสำคัญของกระบวนการพูดคุยเพื่อสันติสุข',
 'politics': 1,
 'human_rights': 0,
 'quality_of_life': 0,
 'international': 0,
 'social': 1,
 'environment': 0,
 'economics': 0,
 'culture': 0,
 'labor': 0,
 'national_security': 1,
 'ict': 0,
 'education': 0}

In [ ]:
pre_result = trainer.predict(test_data_tok.select(range(2)))
topic = [j for i,j in enumerate(tags) if pre_result.label_ids[1][i] == 1]
topic

['politics', 'social', 'national_security']

In [ ]:
# @title
import json, os

run_dir = "wcberta-prachathai67k/checkpoint-27190"  # โฟลเดอร์รันหลักที่มี trainer_state.json
with open(os.path.join(run_dir, "trainer_state.json"), encoding="utf-8") as f:
    st = json.load(f)

print("metric_for_best_model:", st.get("metric_for_best_model"))
print("best_metric:", st.get("best_metric"))
print("best_model_checkpoint:", st.get("best_model_checkpoint"))

metric_for_best_model: None
best_metric: 0.7442904548116338
best_model_checkpoint: wcberta-prachathai67k/checkpoint-27190

In [ ]:
# @title
import json, os

run_dir = "wcberta-prachathai67k/checkpoint-67975"  # โฟลเดอร์รันหลักที่มี trainer_state.json
with open(os.path.join(run_dir, "trainer_state.json"), encoding="utf-8") as f:
    st = json.load(f)

print("metric_for_best_model:", st.get("metric_for_best_model"))
print("best_metric:", st.get("best_metric"))
print("best_model_checkpoint:", st.get("best_model_checkpoint"))

metric_for_best_model: None
best_metric: 0.7612903225806451
best_model_checkpoint: wcberta-prachathai67k/checkpoint-67975

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

best_ckpt = "wcberta-prachathai67k/checkpoint-67975"
export_dir = "wcberta-prachathai67k-best"

model = AutoModelForSequenceClassification.from_pretrained(best_ckpt)
tok   = AutoTokenizer.from_pretrained(best_ckpt)

model.save_pretrained(export_dir)
tok.save_pretrained(export_dir)

# (ถ้าคุณมีไฟล์ mapping ชื่อคลาส)
import json
LABEL_NAMES = ["politics","human_rights","quality_of_life","international","social",
               "environment","economics","culture","labor","national_security","ict","education"]
with open(f"{export_dir}/label_names.json","w",encoding="utf-8") as f:
    json.dump(LABEL_NAMES, f, ensure_ascii=False, indent=2)

In [ ]:
MODEL_DIR = "wcberta-prachathai67k-best"  # โฟลเดอร์ที่ save_pretrained ไว้
MAX_LEN   = 512
THRESH    = 0.5                           # เกณฑ์เริ่มต้น (ปรับได้)

# ----- load -----
tok = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR).eval()

In [ ]:
with open(f"{MODEL_DIR}/label_names.json", encoding="utf-8") as f:
    LABELS = json.load(f)
sigmoid = torch.nn.Sigmoid()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def predict_with_probs(texts: list[str], threshold :float = THRESH , top_k:int = None):
    """
    คืน:
      - probs_sorted: รายชื่อคลาส + prob เรียงจากมากไปน้อย
      - chosen: รายการคลาสที่ “ผ่านเกณฑ์” (threshold หรือ top_k)
    """
    enc = tok(texts, return_tensors="pt", truncation=True, max_length=MAX_LEN, padding=True)
    enc = {k: v.to(device) for k, v in enc.items()}

    with torch.no_grad():
        logits = model(**enc).logits
        probs = sigmoid(logits).cpu().numpy()  # (B, C)

    results = []
    for i, text in enumerate(texts):
        p = probs[i]                                 # ความน่าจะเป็นต่อคลาส
        order = np.argsort(p)[::-1]                  # เรียงมาก→น้อย
        probs_sorted = [(LABELS[j], float(p[j])) for j in order]

        if top_k and top_k > 0:
            chosen = [LABELS[j] for j in order[:top_k]]
        else:
            chosen = []
            for name , prob in probs_sorted:

                if prob >= threshold:
                    chosen.append(name)
                else:
                    break


        results.append({
            "text": text,
            "probs_sorted": probs_sorted,  # ดูอันดับทั้งหมดได้
            "chosen": chosen               # คำตอบหลายคลาส
        })
    return results

### 6. การทำนายผล (Inference)
สร้างฟังก์ชัน `predict_with_probs` สำหรับนำโมเดลที่ฝึกเสร็จแล้วมาใช้งานจริง โดยสามารถเลือกผลลัพธ์ตามเกณฑ์ Threshold หรือเลือกเฉพาะ Top-K ที่มีความมั่นใจสูงสุดได้

In [ ]:
texts = [data_test.loc[0,"body_text"]]
print(texts[0])
print(data_test.loc[0,])

17 พ.ย. 2558 Blognone [1] รายงานว่า กลุ่มแฮคเกอร์ Anonymous ประกาศสงครามไซเบอร์กับกลุ่มหัวรุนแรงหลังจากกลุ่ม IS ออกมาประกาศว่าเป็นผู้อยู่เบื้องหลังการโจมตีกรุงปารีสในคืนวันศุกร์ที่ผ่านมา


ภาพในคลิปใน YouTube โฆษกของกลุ่มแฮคเกอร์สวมหน้ากากที่เป็นสัญลักษณ์ของกลุ่มได้ออกมาอ่านแถลงเป็นภาษาฝรั่งเศส มีใจความว่า จากการโจมตีของกลุ่ม IS ในกรุงปารีส กลุ่ม Anonymous ทั่วโลกจะตามล่ากลุ่ม IS เหมือนที่เคยทำตอนที่มีการโจมตีสำนักพิมพ์ Charlie Hebdo และครั้งนี้จะเป็นปฏิบัติการโจมตีครั้งใหญ่ที่สุดของกลุ่ม Anonymous เลย นอกจากนี้กลุ่ม Anonymous ยังแสดงความเสียใจต่อครอบครัวผู้สูญเสียในเหตุการณ์ครั้งนี้
กลุ่ม Anonymous เคยประกาศสงครามกับกลุ่ม IS หลังจากการโจมตีสำนักพิมพ์ Charlie Hebdo ที่ฝรั่งเศสเมื่อต้นปีที่ผ่านมา ซึ่งครั้งนั้นกลุ่ม Anonymous อ้างว่าได้ระงับบัญชีผู้ใช้งานที่เกี่ยวข้องกับ IS ไปหลายพันบัญชี (อ่านรายละเอียดเพิ่มเติม จากBlognone ที่  กลุ่มแฮคเกอร์ Anonymous ประกาศสงครามไซเบอร์ขอกวาดล้างพวก ISIS [2])
Unnamed: 0                                                           0
url                                  https://prachatai.com/print/62490
date                                                  2015-11-17 18:14
title                แฮคเกอร์ Anonymous ลั่นทำสงครามไซเบอร์ครั้งใหญ...
body_text            17 พ.ย. 2558 Blognone [1] รายงานว่า กลุ่มแฮคเก...
politics                                                             0
human_rights                                                         0
quality_of_life                                                      0
international                                                        1
social                                                               0
environment                                                          0
economics                                                            0
culture                                                              0
labor                                                                0
national_security                                                    0
ict                                                                  1
education                                                            0
Name: 0, dtype: object

In [ ]:
out = predict_with_probs(texts, threshold=None , top_k=3)  # หรือกำหนด top_k=2
print(out[0]["probs_sorted"])  # ดู 5 คลาสที่คะแนนสูงสุด
print("chosen:", out[0]["chosen"])
print(out)

[('ict', 0.9780653119087219), ('international', 0.8076063394546509), ('politics', 0.18912579119205475), ('human_rights', 0.09919323772192001), ('national_security', 0.030139081180095673), ('quality_of_life', 0.00980364065617323), ('social', 0.008862776681780815), ('culture', 0.006962081417441368), ('environment', 0.0060159265995025635), ('economics', 0.0051177311688661575), ('education', 0.0035192708019167185), ('labor', 0.003128827316686511)]
chosen: ['ict', 'international', 'politics']
[{'text': '17 พ.ย. 2558 Blognone [1] รายงานว่า กลุ่มแฮคเกอร์ Anonymous ประกาศสงครามไซเบอร์กับกลุ่มหัวรุนแรงหลังจากกลุ่ม IS ออกมาประกาศว่าเป็นผู้อยู่เบื้องหลังการโจมตีกรุงปารีสในคืนวันศุกร์ที่ผ่านมา\n\n\nภาพในคลิปใน YouTube โฆษกของกลุ่มแฮคเกอร์สวมหน้ากากที่เป็นสัญลักษณ์ของกลุ่มได้ออกมาอ่านแถลงเป็นภาษาฝรั่งเศส มีใจความว่า จากการโจมตีของกลุ่ม IS ในกรุงปารีส กลุ่ม Anonymous ทั่วโลกจะตามล่ากลุ่ม IS เหมือนที่เคยทำตอนที่มีการโจมตีสำนักพิมพ์ Charlie Hebdo และครั้งนี้จะเป็นปฏิบัติการโจมตีครั้งใหญ่ที่สุดของกลุ่ม Anonymous เลย นอกจากนี้กลุ่ม Anonymous ยังแสดงความเสียใจต่อครอบครัวผู้สูญเสียในเหตุการณ์ครั้งนี้\nกลุ่ม Anonymous เคยประกาศสงครามกับกลุ่ม IS หลังจากการโจมตีสำนักพิมพ์ Charlie Hebdo ที่ฝรั่งเศสเมื่อต้นปีที่ผ่านมา ซึ่งครั้งนั้นกลุ่ม Anonymous อ้างว่าได้ระงับบัญชีผู้ใช้งานที่เกี่ยวข้องกับ IS ไปหลายพันบัญชี (อ่านรายละเอียดเพิ่มเติม จากBlognone ที่\xa0\xa0กลุ่มแฮคเกอร์ Anonymous ประกาศสงครามไซเบอร์ขอกวาดล้างพวก ISIS [2])', 'probs_sorted': [('ict', 0.9780653119087219), ('international', 0.8076063394546509), ('politics', 0.18912579119205475), ('human_rights', 0.09919323772192001), ('national_security', 0.030139081180095673), ('quality_of_life', 0.00980364065617323), ('social', 0.008862776681780815), ('culture', 0.006962081417441368), ('environment', 0.0060159265995025635), ('economics', 0.0051177311688661575), ('education', 0.0035192708019167185), ('labor', 0.003128827316686511)], 'chosen': ['ict', 'international', 'politics']}]